### ISSUE TITLE
Error returned from tagme() function

### ISSUE THREAD

**Issue by tabanid** [jbrzusto/motus#17]
When running

t <- tagme(projRecv = 109, update = TRUE, new = TRUE)

I received the following error (including the last few lines of msgs). 

Got 13 runs starting at 0 for batch   1109              Got 26 hits starting   at 0 for batch 1109               Got 131 GPS fixes for batch 1109                Error in function (type, msg,   asError = TRUE)  :        Unknown SSL protocol error in connection to sgdata.motus.org:443    

I (almost immediately) re-ran the tagme() function and it re-started and completed the job.

**Comment by jbrzusto** [comment]
I think this is just due to the server being stopped and restarted.  I've added an option to
shut down the server gracefully (jbrzusto/motusServer#257).  Doing so, the server should finish replying to pending requests before shutting down.  Of course, when the server is down, you'll
get an error, and what that is should probably be clarified.
